Fix AttributeError when printing exceptions
Use the str() function to print exceptions instead of trying to use the
old .message attribute.

Fixes the error:

>  writeln(e.message, out=sys.stderr)
E  AttributeError: 'GitGerritHookDirNotFound' object has no attribute 'message'